In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
xl = pd.ExcelFile("NWM_data_updated-Copy1.xlsx", engine='openpyxl')
a=xl.sheet_names


sheet_no = list(range(2, 32))

In [2]:
#loading the data set
dataframe_collection = {}
i=0
for i in range(30):
    if i==0 :
        dataframe_collection[i] = xl.parse(a[i],converters={"STAID_1":str})
    else:
        dataframe_collection[i] = xl.parse(a[i])

In [3]:


obsflow = dataframe_collection[2]
modelflow= dataframe_collection[29]


column_names = ["dis2sea","landUse","soilTexture1", "soilTexture2","soilTexture3","soilTexture4","soilTexture5","soilTexture6","soilTexture7","soilTexture8","soilTexture9","soilTexture10","topoIndex","drainageArea","ModelFlow","Obsflow"]
k=0
df = pd.DataFrame(columns = column_names) 
for index, row in dataframe_collection[0].iterrows():       
        print(index)   
        sta_id = dataframe_collection[0].iloc[index,0]
        dis2sea=dataframe_collection[0].iloc[index,1]
        land_use=dataframe_collection[0].iloc[index,2]
        soil_texture1=dataframe_collection[0].iloc[index,3]
        soil_texture2=dataframe_collection[0].iloc[index,4]
        soil_texture3=dataframe_collection[0].iloc[index,5]
        soil_texture4=dataframe_collection[0].iloc[index,6]
        soil_texture5=dataframe_collection[0].iloc[index,7]
        soil_texture6=dataframe_collection[0].iloc[index,8]
        soil_texture7=dataframe_collection[0].iloc[index,9]
        soil_texture8=dataframe_collection[0].iloc[index,10]
        soil_texture9=dataframe_collection[0].iloc[index,11]
        soil_texture10=dataframe_collection[0].iloc[index,12]
        topoindex = dataframe_collection[0].iloc[index,13]
        drainagearea =  dataframe_collection[0].iloc[index,14]
        obs = obsflow[sta_id]/drainagearea
        mod0 = modelflow[sta_id]/drainagearea
        
        for i in range(0,490):
            df.loc[k]=[dis2sea]+[land_use]+[soil_texture1]+[soil_texture2]+[soil_texture3]+[soil_texture4]+[soil_texture5]+[soil_texture6]+[soil_texture7]+[soil_texture8]+[soil_texture9]+[soil_texture10]+[topoindex]+[drainagearea]+[mod0[i]]+[obs[i]]
            k=k+1
            
    
df4 =df.dropna()
df4
df4.to_csv('out_lead_26day_data.csv', sep='\t')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384

In [12]:
df

,dis2sea,landUse,soilTexture1,soilTexture2,soilTexture3,soilTexture4,soilTexture5,soilTexture6,soilTexture7,soilTexture8,...,ModelFlow21,ModelFlow22,ModelFlow23,ModelFlow24,ModelFlow25,ModelFlow26,ModelFlow27,ModelFlow28,ModelFlow29,Obsflow
210432,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.183840,0.177885,0.172085,0.166388,0.159922,0.154730,0.152206,0.148942,0.144207,0.334901
210433,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.154117,0.151514,0.141575,0.137644,0.134657,0.133690,0.129105,0.128425,0.126947,0.264926
210434,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.139014,0.138347,0.137169,0.132284,0.130643,0.127873,0.125649,0.125631,0.121316,0.218911
210435,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.129002,0.132464,0.125703,0.126292,0.125030,0.122819,0.120889,0.119032,0.124453,0.200941
210436,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.147013,0.150078,0.151839,0.149964,0.148023,0.145727,0.144904,0.141791,0.140174,0.227624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210975,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.037885,0.037638,0.037272,0.037121,0.036659,0.036340,0.036016,0.035727,0.035499,0.064530
210976,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.040264,0.039357,0.039044,0.038444,0.037764,0.037248,0.036875,0.036526,0.036244,0.047921
210977,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.037873,0.037548,0.037248,0.036887,0.036532,0.036238,0.035871,0.035517,0.035216,0.038391
210978,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.039387,0.039002,0.038618,0.038191,0.037758,0.037374,0.037025,0.036725,0.036358,0.048738
210979,5.158558,3.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,0.040907,0.040727,0.040337,0.040030,0.039724,0.039417,0.039087,0.038726,0.038311,0.066980

In [8]:
df4.to_csv('out_lead0-15_data.csv', sep='\t')

In [9]:
df4

,dis2sea,landUse,soilTexture1,soilTexture2,soilTexture3,soilTexture4,soilTexture5,soilTexture6,soilTexture7,soilTexture8,...,ModelFlow7,ModelFlow8,ModelFlow9,ModelFlow10,ModelFlow11,ModelFlow12,ModelFlow13,ModelFlow14,ModelFlow15,Obsflow
15,3.974170,1.0,3.0,3.0,3.0,7.0,12.0,12.0,12.0,12.0,...,0.002253,0.002712,0.001927,0.002357,0.002345,0.001932,0.001904,0.001760,0.002706,0.000764
16,3.974170,1.0,3.0,3.0,3.0,7.0,12.0,12.0,12.0,12.0,...,0.004386,0.004899,0.001944,0.001669,0.001783,0.003853,0.001904,0.001881,0.001732,0.001008
17,3.974170,1.0,3.0,3.0,3.0,7.0,12.0,12.0,12.0,12.0,...,0.001950,0.002827,0.001792,0.001686,0.003028,0.001915,0.002036,0.003463,0.001881,0.013613
18,3.974170,1.0,3.0,3.0,3.0,7.0,12.0,12.0,12.0,12.0,...,0.003135,0.002930,0.003475,0.004931,0.007167,0.002294,0.003779,0.003039,0.001806,0.002536
19,3.974170,1.0,3.0,3.0,3.0,7.0,12.0,12.0,12.0,12.0,...,0.003039,0.008257,0.003492,0.005075,0.005115,0.004117,0.002202,0.003234,0.002110,0.003897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164206,0.431609,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,...,0.045633,0.049437,0.050676,0.057567,0.048926,0.036716,0.033184,0.034388,0.035425,0.058287
164207,0.431609,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,...,0.049933,0.046412,0.051037,0.050996,0.060168,0.050500,0.036537,0.033902,0.035438,0.050309
164208,0.431609,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,...,0.047730,0.049960,0.046831,0.051374,0.051875,0.062752,0.051298,0.036715,0.033542,0.048944
164209,0.431609,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,...,0.069503,0.049020,0.050084,0.046256,0.050736,0.053464,0.066053,0.051398,0.036102,0.057568
164210,0.431609,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,...,0.072700,0.069037,0.049210,0.049873,0.044794,0.050682,0.054323,0.068947,0.051106,0.064396

In [10]:
for i in range(29,30):
    print(i)

29

In [14]:
df= df.dropna()
df.to_csv('340train.csv')

In [20]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(df['ModelFlow'] , df['Obsflow'] )

0.10373442473316054

In [9]:
correl = df["ModelFlow"].corr(df["Obsflow"])
print(correl)

0.6633008723560679

In [16]:
df['mean_d'] = df[["dis2sea","landUse","soilTexture1", "soilTexture2","soilTexture3","soilTexture4","soilTexture5","soilTexture6","soilTexture7","soilTexture8","soilTexture9","soilTexture10","topoIndex","drainageArea"]].mean(axis=1).astype(float)

cols = ["ModelFlow","mean_d","Obsflow"]
df2=df[cols]
df2

        ModelFlow     mean_d   Obsflow
0        0.002242  14.539496  0.001403
1        0.001846  14.539496  0.000948
2        0.003463  14.539496  0.000813
3        0.004857  14.539496  0.002754
4        0.001812  14.539496  0.003455
...           ...        ...       ...
146966   0.110553   8.022577  0.518755
146967   0.307812   8.022577  0.551250
146968   0.241137   8.022577  0.242550
146969   0.182300   8.022577  0.248353
146970   0.141547   8.022577  0.154350

[146971 rows x 3 columns]

In [18]:
df3 = df2[df.isna().any(axis=1)]
df3

        ModelFlow     mean_d   Obsflow
82            NaN  14.539496  0.002936
83            NaN  14.539496  0.001676
84            NaN  14.539496  0.000805
85            NaN  14.539496  0.000673
91            NaN  14.539496  0.000514
...           ...        ...       ...
146805        NaN   8.022577  0.011234
146806        NaN   8.022577  0.012302
146807        NaN   8.022577  0.012069
146844        NaN   8.022577  0.009841
146854        NaN   8.022577  0.011083

[11502 rows x 3 columns]

In [19]:
df4 = df2.dropna()
df4

        ModelFlow     mean_d   Obsflow
0        0.002242  14.539496  0.001403
1        0.001846  14.539496  0.000948
2        0.003463  14.539496  0.000813
3        0.004857  14.539496  0.002754
4        0.001812  14.539496  0.003455
...           ...        ...       ...
146966   0.110553   8.022577  0.518755
146967   0.307812   8.022577  0.551250
146968   0.241137   8.022577  0.242550
146969   0.182300   8.022577  0.248353
146970   0.141547   8.022577  0.154350

[135469 rows x 3 columns]

In [20]:
df4 = df2.dropna()
df4
df4.to_csv('out_340station.csv', sep='\t')

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split

x, y = df4.iloc[:, 0:2], df4.iloc[:,2]

y = y.values.reshape(y.shape[0],1)
print(y)
x_train, x_test, y_train, y_test = \
    train_test_split(x, y, test_size=0.2, 
                                 random_state=0)

[[0.00140285]
 [0.00094822]
 [0.00081314]
 ...
 [0.04894359]
 [0.05756801]
 [0.06439567]]

In [11]:
y.shape

(151009, 1)

In [12]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train_std = sc.fit_transform(x_train)
x_test_std = sc.transform(x_test)
#y_train_std = sc.fit_transform(y_train.values.reshape(y_train.shape[0],1))
#y_test_std = sc.transform(y_test.values.reshape(y_test.shape[0],1))

In [13]:
x_train_std = x_train_std.reshape(x_train.shape[0],x_train.shape[1],1)
x_test_std = x_test_std.reshape(x_test.shape[0],x_test.shape[1],1)
x_train_std.shape

(120807, 2, 1)

In [14]:
TimeSteps=x.shape[1]
TotalFeatures=1
print(TimeSteps)

2

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
 
# Initialising the RNN
regressor = Sequential()
 
# Adding the First input hidden layer and the LSTM layer
# return_sequences = True, means the output of every time step to be shared with hidden next layer
regressor.add(LSTM(units = 10, activation = 'relu', input_shape = (TimeSteps, TotalFeatures), return_sequences=True))
 
# Adding the Second Second hidden layer and the LSTM layer
regressor.add(LSTM(units = 5, activation = 'relu', input_shape = (TimeSteps, TotalFeatures), return_sequences=True))
 
# Adding the Second Third hidden layer and the LSTM layer
regressor.add(LSTM(units = 5, activation = 'relu', return_sequences=False ))
 
regressor.add(Dense(units = 1))
 
# Compiling the RNN
regressor.compile(optimizer = 'rmsprop', loss = 'mean_squared_error',metrics=['mae'])
 
##################################################
 
import time
# Measuring the time taken by the model to train
StartTime=time.time()
 
# Fitting the RNN to the Training set
regressor.fit(x_train_std, y_train,validation_data=(x_test_std, y_test), batch_size = 5, epochs = 20)
 
EndTime=time.time()
print("## Total Time Taken: ", round((EndTime-StartTime)/60), 'Minutes ##')

Epoch 1/20
24162/24162 [==============================] - 59s 2ms/step - loss: 3.8367 - mae: 0.3089 - val_loss: 3.1227 - val_mae: 0.2968
Epoch 2/20
24162/24162 [==============================] - 57s 2ms/step - loss: 2.4289 - mae: 0.2586 - val_loss: 2.8656 - val_mae: 0.2519
Epoch 3/20
24162/24162 [==============================] - 56s 2ms/step - loss: 2.1683 - mae: 0.2546 - val_loss: 2.3845 - val_mae: 0.3172
Epoch 4/20
24162/24162 [==============================] - 56s 2ms/step - loss: 2.0387 - mae: 0.2546 - val_loss: 2.1557 - val_mae: 0.2399
Epoch 5/20
24162/24162 [==============================] - 55s 2ms/step - loss: 1.9691 - mae: 0.2539 - val_loss: 2.0811 - val_mae: 0.2309
Epoch 6/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.8791 - mae: 0.2498 - val_loss: 1.9934 - val_mae: 0.2257
Epoch 7/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.8456 - mae: 0.2492 - val_loss: 1.8871 - val_mae: 0.2229
Epoch 8/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.7913 - mae: 0.2466 - val_loss: 1.6985 - val_mae: 0.2206
Epoch 9/20
24162/24162 [==============================] - 58s 2ms/step - loss: 1.7483 - mae: 0.2447 - val_loss: 1.7010 - val_mae: 0.2450
Epoch 10/20
24162/24162 [==============================] - 57s 2ms/step - loss: 1.6894 - mae: 0.2439 - val_loss: 1.5642 - val_mae: 0.2323
Epoch 11/20
24162/24162 [==============================] - 57s 2ms/step - loss: 1.6331 - mae: 0.2436 - val_loss: 1.5396 - val_mae: 0.2153
Epoch 12/20
24162/24162 [==============================] - 54s 2ms/step - loss: 1.6350 - mae: 0.2434 - val_loss: 1.4963 - val_mae: 0.2161
Epoch 13/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.6293 - mae: 0.2428 - val_loss: 2.0282 - val_mae: 0.2309
Epoch 14/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.6793 - mae: 0.2448 - val_loss: 1.7924 - val_mae: 0.2288
Epoch 15/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.6668 - mae: 0.2452 - val_loss: 1.4838 - val_mae: 0.2261
Epoch 16/20
24162/24162 [==============================] - 56s 2ms/step - loss: 1.9398 - mae: 0.2513 - val_loss: 3.1860 - val_mae: 0.2955
Epoch 17/20
24162/24162 [==============================] - 57s 2ms/step - loss: 2.0032 - mae: 0.2509 - val_loss: 2.9725 - val_mae: 0.2419
Epoch 18/20
24162/24162 [==============================] - 59s 2ms/step - loss: 2.4787 - mae: 0.2532 - val_loss: 2.7391 - val_mae: 0.2409
Epoch 19/20
24162/24162 [==============================] - 55s 2ms/step - loss: 2.3887 - mae: 0.2515 - val_loss: 2.6377 - val_mae: 0.2641
Epoch 20/20
24162/24162 [==============================] - 56s 2ms/step - loss: 2.3343 - mae: 0.2504 - val_loss: 2.5438 - val_mae: 0.2289
## Total Time Taken:  19 Minutes ##

In [16]:
regressor.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm (LSTM)                  (None, 2, 10)             480
_________________________________________________________________
lstm_1 (LSTM)                (None, 2, 5)              320
_________________________________________________________________
lstm_2 (LSTM)                (None, 5)                 220
_________________________________________________________________
dense (Dense)                (None, 1)                 6
=================================================================
Total params: 1,026
Trainable params: 1,026
Non-trainable params: 0
_________________________________________________________________

In [21]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTMss
 
# Initialising the RNN
regressor = Sequential()
 
# Adding the First input hidden layer and the LSTM layer
# return_sequences = True, means the output of every time step to be shared with hidden next layer
regressor.add(LSTM(units = 10, activation = 'relu', input_shape = (TimeSteps, TotalFeatures), return_sequences=True))
 
# Adding the Second Second hidden layer and the LSTM layer
regressor.add(LSTM(units = 5, activation = 'relu', input_shape = (TimeSteps, TotalFeatures), return_sequences=True))
 
# Adding the Second Third hidden layer and the LSTM layer
regressor.add(LSTM(units = 5, activation = 'relu', return_sequences=False ))
 
regressor.add(Dense(units = 1))
 
# Compiling the RNN
regressor.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

 
##################################################
 
import time
# Measuring the time taken by the model to train
StartTime=time.time()
 
# Fitting the RNN to the Training set
regressor.fit(x_train_std, y_train,validation_data=(x_test_std, y_test) ,batch_size = 5, epochs = 10)
 
EndTime=time.time()
print("## Total Time Taken: ", round((EndTime-StartTime)/60), 'Minutes ##')

Epoch 1/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 2/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 3/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 4/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 5/10
24162/24162 [==============================] - 59s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 6/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 7/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 8/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 9/10
24162/24162 [==============================] - 58s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
Epoch 10/10
24162/24162 [==============================] - 59s 2ms/step - loss: 6.6133e-08 - acc: 0.0092 - val_loss: 6.6751e-08 - val_acc: 0.0096
## Total Time Taken:  10 Minutes ##

In [22]:
regressor.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_3 (LSTM)                (None, 2, 10)             480
_________________________________________________________________
lstm_4 (LSTM)                (None, 2, 5)              320
_________________________________________________________________
lstm_5 (LSTM)                (None, 5)                 220
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6
=================================================================
Total params: 1,026
Trainable params: 1,026
Non-trainable params: 0
_________________________________________________________________